### PR TITLE
Some cleanup, added support for loading Uri via LoadMedia(string), WPF sample update to support both Uris and Filepaths and show (in comments) how to inject the player control dynamically

### PR DESCRIPTION
**Pull request by birbilis**

### CODE REVIEW

**Comment by birbilis** [comment]
Thanks. I'm happy to also inform you that I've just managed to use xZune.Vlc succesfully at FoscamController project (http://FoscamController.codeplex.com) to display the H.264/RTSP stream from an HD model of a Foscam PTZ IP Camera

**Comment by higankanshi** [comment]
Congratulations! I should also thank you for your contribution to xZune.Vlc.

**Comment by birbilis** [comment]
You're welcome

**Comment by birbilis** [comment]
Btw, I found out that --rtsp-tcp option is needed for the RTSP stream to pass through VPN (OpenVPN) and also that Foscam HD cameras seem to send some broken frames (judging from VLC's logging) at connect. Live555 library that VLC uses doesn't seem to have problem with it, but it must be choking FFMPEG (eg tried first with WebEye library that makes use of it and it was showing half a frame, then freezing). Onvif Device Manager from Sourceforge which also uses FFMPEG seems to work though with Foscam HD cams, so it must be some FFMPEG setting. Glad VLC worked without much hasle

**Comment by higankanshi** [comment]
Ummm, I want to warp a managed ffmpeg. Vlc have so much issue with .Net, and we can't control everything of media.

Actually I'm doing it now. But I lost much code...
Ummm...If I have time, maybe I'll do it.

**Comment by birbilis** [comment]
Why don't you use https://github.com/jacobbo/WebEye that already has wrapped FFMPEG? 
Or borrow code from ONVIF Device Manager that also has done similarly? (http://sourceforge.net/projects/onvifdm/), though using WebEye's wrapper is easier (OnvifDM has huge codebase)

However as I wrote, FFMPEG has issues with RTSP (have read older complaints about it elsewhere, but also had the problem with the broken RTSP stream using WebEye myself too as I was saying above)

**Pull request merged**
