### PR TITLE
- added note to Sample's AssemblyInfo regarding the need to use --rtcp-tcp to connnect to RTSP stream through a VPN (e.g. for IP Camera behind firewall). Else one sees no video

### PR DESCRIPTION
**Pull request by birbilis**
…p-tcp VLC parameter to pass RTSP through a VPN (e.g if you want to access some IP Camera behind a firewall by tunneling to its local network via VPN)

### CODE REVIEW

**Comment by higankanshi** [comment]
If I have time, I want to warp vlc's options by some classes.
But they are too complex ...

**Comment by birbilis** [comment]
indeed, a long list of VLC params is here:
https://wiki.videolan.org/VLC_command-line_help
maybe one could build a parser for that text ;-) or parse and convert some code (Java or whatever) from other library that may have the Vlc params wrapped as constants (or similar) already

but was just bitten by some mistake at https://wiki.videolan.org/Command_line/ where it says that --intf is same as -I, but I don't see --intf dummy working whereas -I dummy does work (btw, I saw you were passing "-I" and "dummy" as two parameters, changed it to "-I dummy" since it is supposed to be a single one)

**Comment by birbilis** [comment]
btw, I noticed some inconsistencies:
1) VlcPlayer.Wpf constructor takes a VlcOption param instead of a VlcOptions (maybe other constructors too). 
2) That parameter is a string[] and also the Class Attribute that one can use instead seems to use a string[] for the options. However, the two LoadMediaWithOptions methods seem to take a string instead of a string[]

**Comment by birbilis** [comment]
(didn't change anything there to avoid breaking compatibility with existing client code that may use your control)

**Comment by higankanshi** [comment]
You are right, I don't make it in same.
It's my mistake. I can fix it.

**Comment by birbilis** [comment]
Maybe add some overloaded method and constructor

**Comment by birbilis** [comment]
...and add some method attribute to deprecate the old ones (there should be some attribute for this in .net I think)

**Comment by higankanshi** [comment]
Ok, I have done it.
BTW, Do you use any plug-in for cleaning up code?

**Comment by birbilis** [comment]
Not really, but I do use some productivity tools. I just compiled a list of the VS2015 extensions I use on my main machine at: https://zoomicon.wordpress.com/2015/11/13/visual-studio-2015-extensions-i-use/

**Comment by birbilis** [comment]
forgot to mention that indeed from that list of extensions I use the Power Tools one, has a "Power Commands > Remove and Sort Usings" action that one can right click and run on the whole solution

there is another nice extension called Remove unused references that is not available for VS2015, but only for VS2013 (think you can edit its .vsix and make it work for it too though, see Q&A at its extension page). I usually open up the solution in VS2013 too just to run that. Alternative is to use the Copy References extension and right click a reference under the References subtree of a project, then select "Copy Reference", then Remove the reference and rebuild that project. If rebuild fails, then right click at the References again and select Paste Reference. Then repeat till you remove all references that are not needed

**Pull request merged**
